### PR TITLE
Dynamically add pan to new loaded images

### PR DESCRIPTION
**Pull request by MobCode100**
Hi, jmalarcon, thank you for writing such great jquery plugin! I'm using this for my projects.

I would like to open a pull request. The changes that I've made are small, adding 2 if statement and 2 more variables which are:
1. init, for initializing the panWrapper
2. addImage, for adding new images into the finalSet variable
3. Extend loading animation to 400ms

The loading animation is extended because I've noticed slight image flicker after clicking them to zoom, which for me not very eye pleasing.

This is my first time opening a pull request, any mistakes that i've made, do tell me so 🙏.

Thank you so much for your time and attention.

### CODE REVIEW

**Comment by jmalarcon** [comment]
Hi @MobCode100 

Thanks for your pull request. I've been reviewing it and made many changes to your original code to simplify it and specially to ease the use of new parameters. Now it takes an `options` object parameter to specify the needed options as explained in the new readme:

- There's no need to specify a new parameter to indicate the initialization of the plugin. I've modified [the original code](https://github.com/saplumbaga/jquery.pan) that was not very well crafted to include everything under the same auto-callable function at the end, so that it could use private values in successive calls. This way it's easy to detect a call is the first or not, therefore saving us to use an `init` parameter that is easy to use incorrectly.
- There's no need to use a parameter to make it work with successive images. I've removed it. Now simple call `pan` with any dynamically added image and it it will simply work.
- I don't see a good case for using a delay showing the images, but I kept that functionality for you in the form of a new parameter in the options called `minLoadingTime` that defaults to 0. If you use a number such as 400 (take a look to the example in `index.html`) it will delay showing the image as you wanted.
- I've removed the use of `let` because this plugin supports Internet Explorer and it doesn't support that way of declaring variables.

I've added all this to the Pull Request and changed the version to 5.0 since it breaks changes with the previous one (although I've added a check to make it 100% compatible, the old parameter is deprecated).

Take a look at the new final code.

Thanks for your contribution!

**Review by MobCode100 — COMMENTED** [review]
Very sorry for the very late reply & thank you for all the changes. I've looked at it and everything looks great. Plus, I've learned something by reading your codes. Thank you! 👏

**Comment by MobCode100** [comment]
> 



> * I don't see a good case for using a delay showing the images, but I kept that functionality for you in the form of a new parameter in the options called `minLoadingTime` that defaults to 0. If you use a number such as 400 (take a look to the example in `index.html`) it will delay showing the image as you wanted.

It is not a feature, but just to make it more pleasing to the eye, because without the delay, the image would quickly move from top left to the center after clicking it. So the delay is just to wait for the image to finalize its position. Thanks again for including it in the new release!

Edit: I did consider to change the css so that the image would initially loaded in center position, I have tried that, but didn't work well (need help in that 😅). If this can be achieved, maybe the option `minLoadingTime` can be removed.

**Comment by jmalarcon** [comment]
Thank you for bringing this up and for your pull request.

Interesting what you say about the positioning. I'll take a look at it when I have the time and try to fix that effect you mention. Maybe I've not used it with very big images that take a lot of time to load, and didn't notice it.

I'll let you know.

Cheers.

**Pull request merged**
